apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keti-gpu-metric-collector
  namespace: gpu
spec:
  selector:
    matchLabels:
      name: gpu-metric-collector
  template:
    metadata:
      labels:
        name: gpu-metric-collector
    spec:
      serviceAccountName: keti-gpu-device-plugin
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      containers:
        - name: gpu-metric-collector
          image: ketidevit2/kmc-metric-test:v274
          args:
          - --collecttime=15
          volumeMounts:
            - name: cpuinfo
              mountPath: /proc
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
      - name: cpuinfo
        hostPath:
          path: /proc
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0


