apiVersion: v1
kind: Service
metadata:
  name: metric-collector
  namespace: gpu
  labels:
    name: metric-collector
spec:
  type: LoadBalancer
  ports:
  - port: 2052
    targetPort: 2052
    nodePort: 32052
    protocol: TCP
  selector:
    name: metric-collector