apiVersion: v1
kind: ServiceAccount
metadata:
  name: metric-collector
  namespace: gpu
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metric-collector
  namespace: gpu
subjects:
- kind: ServiceAccount
  name: metric-collector
  namespace: gpu
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: metric-collector
  namespace: gpu
  labels:
    name: metric-collector
spec:
  type: LoadBalancer
  ports:
  - port: 2052
    targetPort: 2052
    nodePort: 32052
    protocol: TCP
  selector:
    name: metric-collector
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: keti-gpu-metric-collector
  namespace: gpu
spec:
  selector:
    matchLabels:
      name: gpu-metric-collector
  template:
    metadata:
      labels:
        name: gpu-metric-collector
    spec:
      nodeSelector: 
        gpu: "true"
      serviceAccountName: keti-gpu-device-plugin
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      containers:
        - name: gpu-metric-collector
          image: ketidevit2/kmc-metric-test:v284
          args:
          - --collecttime=5
          - --DegradationPersent=15
          volumeMounts:
            - name: cpuinfo
              mountPath: /proc
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      volumes:
      - name: cpuinfo
        hostPath:
          path: /proc
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0


